# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CryptoPrice' do
  use_frameworks!

  # Pods for CryptoPrice
    pod 'Alamofire'
    pod 'SwiftChart', '1.0.1'

end
